In [1]:
import pandas as pd
import numpy as np

In [3]:
np.random.seed(42)
ser_1 = pd.Series(np.random.randint(0,10,4))
ser_1

0    6
1    3
2    7
3    4
dtype: int32

In [4]:
df = pd.DataFrame(np.random.randint(0,10,(3,4)),
                  columns = ['a','b','c','d'])
df

   a  b  c  d
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [5]:
np.exp(ser_1)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [6]:
np.sin(df*np.pi/4)

          a             b         c             d
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [7]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 39538223, 'Texas': 29145505,
                        'Florida': 21538187}, name='population')

In [8]:
population/area

Alaska              NaN
California    93.257784
Florida             NaN
Texas         41.896072
dtype: float64

In [10]:
a = pd.Series([2,4,6],index=[0,1,2])
b = pd.Series([1,3,5],index=[1,2,3])

print(a)
print(b)
a+b

0    2
1    4
2    6
dtype: int64
1    1
2    3
3    5
dtype: int64

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [11]:
a.add(b,fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [13]:
a = pd.DataFrame(np.random.randint(0,20,(2,2)),
                                   columns=['A','B'])
a

   A   B
0  1  11
1  5   1

In [15]:
b = pd.DataFrame(np.random.randint(0,10,(3,3)),
                                   columns=['B','C','D'])
b

   B  C  D
0  3  8  2
1  4  2  6
2  4  8  6

In [16]:
a+b

    A     B   C   D
0 NaN  14.0 NaN NaN
1 NaN   5.0 NaN NaN
2 NaN   NaN NaN NaN

In [17]:
a.add(b,fill_value = a.values.mean())

     A     B     C     D
0  5.5  14.0  12.5   6.5
1  9.5   5.0   6.5  10.5
2  NaN   8.5  12.5  10.5

In [18]:
np.random.seed(42)
a = np.random.randint(10,size=(3,4))
a

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]], dtype=int32)

In [19]:
a-a[0]

array([[ 0,  0,  0,  0],
       [ 0,  6, -5,  2],
       [ 1,  1, -4,  3]], dtype=int32)

In [20]:
df = pd.DataFrame(a, columns=['A','B','C','D'])
df

   A  B  C  D
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7

In [24]:
df.iloc[0] - df

   A  B  C  D
0  0  0  0  0
1  0 -6  5 -2
2 -1 -1  4 -3

In [26]:
df.subtract(df['B'], axis = 0)

   A  B  C  D
0  3  0  4  1
1 -3  0 -7 -3
2  3  0 -1  3

In [27]:
df

   A  B  C  D
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7

In [30]:
df.loc[1:,'D']

1    6
2    7
Name: D, dtype: int32